### PR TITLE
Add support for osx builds in Travis

### LINKED ISSUE #9: Inadequate CI
Travis is pretty inadequate for a project of this type where what's really required is a selection of build slaves for the supported platforms and python versions.

It seems like currently travis builds on linux x64 only, with python 2.7.

Raising this issue in case anyone knows of a free hosted CI platform that supports other platform types (32 bit, OS X, Windows), has a cunning free solution to the problem, or is willing to donate an instance to the problem. 

OS:
- [x] Linux
- [x] OS X
- [x] Windows

Platform:
- [X] x64
- [ ] x86

### PR DESCRIPTION
**Pull request by naufraghi**
Related to Issue #9 

Given the fact the Python language support in Travis is currently broken, see https://travis-ci.org/naufraghi/rust-cpython/jobs/198527502, we use the declarative matrix syntax for Linux, and we manually generate the osx matrix, installing Python in a `before_install` step using brew.

The same generation code is used to generate the `allow_failures` block.

### CODE REVIEW

**Comment by naufraghi** [comment]
Hi @dgrunwald, here is a working setup with osx support.

The second commit is just an experiment, the "stable" string is supported and working if you prefer.

Let me know for any requested change or for discussion.

**Comment by dgrunwald** [comment]
The failing nightlies are due to `tests/check_symbols.py`.

Is there some way to get that working on OS X? The script needs to find the Python dynamic library and read the exported symbols from it.
If that's not easily doable, change `check_symbols.py` to be a no-op on OS X. (similar to how the script is special-casing Windows).

**Comment by naufraghi** [comment]
I'll have a look

**Comment by naufraghi** [comment]
@dgrunwald I've discovered something, but I didn't understand exactly what the test is testing, so:

On _Linux_ the `nm` tool has a similar output of `readelf`:

```
09:40 gio 23 feb (master)$ nm -D /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so | grep PyList_
0000000000155b70 T PyList_Append
000000000014a450 T PyList_AsTuple
0000000000159ae0 T _PyList_Extend
000000000018a8b0 T PyList_Fini
000000000018ca90 T PyList_GetItem
0000000000156b00 T PyList_GetSlice
000000000018bb70 T PyList_Insert
000000000018cbe0 T PyList_New
000000000014a4d0 T PyList_Reverse
000000000018af70 T PyList_SetItem
00000000001568f0 T PyList_SetSlice
000000000018ade0 T PyList_Size
0000000000159590 T PyList_Sort
000000000055fe20 D PyList_Type
```

On _Darwin_ I heve to use a different option to print this:

```
naufraghi@bonobo ~> nm -g /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python | grep PyList_
000000000002b6d7 T _PyList_Append
000000000002c72b T _PyList_AsTuple
000000000002b334 T _PyList_Fini
000000000002b4d8 T _PyList_GetItem
000000000002b77f T _PyList_GetSlice
000000000002b5f2 T _PyList_Insert
000000000002b36f T _PyList_New
000000000002c6c3 T _PyList_Reverse
000000000002b54f T _PyList_SetItem
000000000002b82d T _PyList_SetSlice
000000000002b4a8 T _PyList_Size
000000000002bdc2 T _PyList_Sort
0000000000108170 D _PyList_Type
000000000002bbd8 T __PyList_Extend
```

If I use `-g` on _Linux_ the error is "no symbols", if I use `-D` on _Darwin_ the error is "File format has no dynamic symbol table."

Is this something interesting for you?

PS. If you are dubious about the `Python` file, it seems a lib:
```
naufraghi@bonobo ~> file /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python
/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python: Mach-O 64-bit dynamically linked shared library x86_64
# and
naufraghi@bonobo ~> ll /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib 
lrwxr-xr-x  1 naufraghi  admin     9B 17 Dic 21:05 /usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib -> ../Python
```

**Comment by markbt** [comment]
I added very basic OSX support in https://github.com/dgrunwald/rust-cpython/pull/171, using just the system Python (which is 2.7).  I think that's probably sufficient, but if you want to make it also work for Python 3 on OS X, please feel free to update this PR (I promise to do a better job of reviewing and accepting this time).

Probably all versions of Python 3 is excessive.  Maybe just 3.7 is enough.

**Comment by markbt** [comment]
Closing as we have some OSX build support in Travis, which should do for now.

**Pull request closed without merging**
