### PR TITLE
doc(readme) Fix the extension example

### PR DESCRIPTION
**Pull request by Hywan**
Thanks for the great project!

Without this patch, the example were not working on my computer with Python 3. I hope it's OK!

### CODE REVIEW

**Comment by dgrunwald** [comment]
As the comment before that line says: "librust2py" must be the name of the `.so` or `.pyd` file
I think it's platform-dependent whether cargo prepends `lib`. Changing this line might fix it for Windows, but breaks it for Linux (and vice versa).

**Comment by Hywan** [comment]
The library name starts with `lib`, but anyway, it's probably a macOS specific thing.

**Comment by dgrunwald** [comment]
So Python prepends `lib` when searching for an extension module on macOS? `import name` -> `libname.dylib`? Though I believe it would also find `name.so` on MacOS.

I think this change is fine, having a `lib` in the init function name is unusual (would require `import libname` from Python). But the comment needs to be adjusted as well then, because extension modules on Windows are typically named `name.pyd` without a lib prefix.

**Comment by Hywan** [comment]
The lib is correctly found, but Python tells me that the `PyInit_rust2py` must be declared, and _not_ `PyInit_librust2py`.

**Pull request closed without merging**
